# Transformations
source('cvs/cvs_mo_phase1_new.R')

########################################################################################################
saveToHdfs <- function(df, host, path) {
  writeToHdfs(df, host,path)
  print("done !!!")
}

########################################################################################################


prepareMoCampaignTable <- function() {
  
  LoadSources(iw.sources.POC_MBR_OPPTY_SAMPLE)
  print("Phase 1 join starting")
  
  completeTable = prepare_p2_table()
  currentDate <- Sys.Date()
  
  transformedTable <- iwSelect(
    completeTable, "*",
      #NORMALIZED_DAY_SPLY_QTY
      "CASE WHEN PHMCY_DAY_SPLY_QTY BETWEEN 1 AND 33 THEN 30 WHEN PHMCY_DAY_SPLY_QTY BETWEEN 34 AND 83 THEN 60 WHEN PHMCY_DAY_SPLY_QTY >= 84 THEN 90 END AS NORMALIZED_DAY_SPLY_QTY",
      #MBR_CURR_AGE
      paste("FLOOR(datediff(from_unixtime(unix_timestamp()), MBR_ACC_MBR_BRTH_DT) / 365) as MBR_CURR_AGE", sep = "", collapse = ""),
      #MINOR_IND
      paste("CASE WHEN FLOOR(datediff(from_unixtime(unix_timestamp()), MBR_ACC_MBR_BRTH_DT) / 365) < 18 THEN 'Y' ELSE 'N' END AS MINOR_IND", sep = "", collapse = ""),
      #MBR_CURR_ELIG_IND
      paste("CASE WHEN '", currentDate , "' BETWEEN MBR_ACC_CVRG_CVRG_EFF_DT and MBR_ACC_CVRG_CVRG_EXPRN_DT THEN 'Y' ELSE 'N' END AS MBR_CURR_ELIG_IND", sep = "", collapse = ""),
      #MCV_IND
      "CASE WHEN (BNFT_PLAN_RCP_OPTNS_MAINT_CHOICE_TYP_CD='MV' AND PHMCY_DAY_SPLY_QTY BETWEEN 21 AND 33 AND PHMCY_DLVRY_SYSTM_CD = 'R' ) 
              OR (BNFT_PLAN_RCP_OPTNS_MAINT_CHOICE_TYP_CD ='MV' AND PHMCY_DAY_SPLY_QTY >= 84 AND PHMCY_DENORM_CVS_RTL_IND = 'N' AND PHMCY_DENORM_CVS_MAIL_IND='N' )
              THEN 'Y' ELSE 'N' END AS MCV_IND",
      #CONTROLLED_SUBSTANCE_IND
      "CASE WHEN (DRUG_DEA_CLS_CD = '0' OR DRUG_DEA_CLS_CD = ' ') THEN 'N' ELSE 'Y' END AS CONTROLLED_SUBSTANCE_IND",
      #RFM_IND
      "CASE WHEN (MBR_PGM_RX_SCHD_HIST_SCH_PGM_ID = 5383 OR MBR_PGM_RX_SCHD_HIST_SCH_PGM_ID = 5384) AND (MBR_PGM_RX_SCHD_HIST_SCHD_OPT_IN_PRCS_SRC_CD = 'PTL' OR MBR_PGM_RX_SCHD_HIST_SCHD_OPT_IN_PRCS_SRC_CD = 'CPT' OR MBR_PGM_RX_SCHD_HIST_SCHD_OPT_IN_PRCS_SRC_CD = 'PSV' OR MBR_PGM_RX_SCHD_HIST_SCHD_OPT_IN_PRCS_SRC_CD = 'CPV') AND (MBR_PGM_RX_SCHD_HIST_SCHD_OPT_OUT_DT is NULL OR MBR_PGM_RX_SCHD_HIST_SCHD_OPT_OUT_DT = '') THEN 'Y' ELSE 'N' end as RFM_IND",
      #RTM_IND
      "CASE WHEN BNFT_PLAN_RCP_OPTNS_MAIL_IND = 'Y' AND PHMCY_DLVRY_SYSTM_CD = 'R' THEN 'Y' ELSE 'N' END AS RTM_IND",
      #FFM_IND
      "CASE WHEN BNFT_PLAN_RCP_OPTNS_MAIL_IND = 'Y' AND PHMCY_DLVRY_SYSTM_CD = 'M' AND EPH_GRP_MAIL_IND_CNT_FOR_EPHLINK = 1 THEN 'Y' ELSE 'N' END AS FFM_IND"
  )
  
  createTms <- paste("'" ,Sys.time() , "'" ," as CREATE_TMS", sep = "")
  #rename columns
  transformedTable <- iwSelect(transformedTable, 
      " 123 as MBR_OPPTY_GID", "MBR_ACC_EPH_LINK_ID as EPH_LINK_ID", "DRUG_GPI4_CD as GPI4_CD", " PHMCY_LVL1_ACCT_GID as LVL1_ACCT_GID", 
      " PHMCY_LVL3_ACCT_GID as LVL3_ACCT_GID",  " CLNT_ACCT_DENORM_LVL0_ACCT_ID as LVL0_ACCT_ID", " CLNT_ACCT_DENORM_LVL0_ACCT_NM as LVL0_ACCT_NM", 
      " CLNT_ACCT_DENORM_LVL0_EFF_DT as LVL0_EFF_DT", " CLNT_ACCT_DENORM_LVL0_EXPRN_DT as LVL0_EXPRN_DT", " CLNT_ACCT_DENORM_LVL1_ACCT_ID as LVL1_ACCT_ID", 
      " CLNT_ACCT_DENORM_LVL1_ACCT_NM as LVL1_ACCT_NM", " CLNT_ACCT_DENORM_LVL1_EFF_DT as LVL1_EFF_DT", " CLNT_ACCT_DENORM_LVL1_EXPRN_DT as LVL1_EXPRN_DT", 
      " CLNT_ACCT_DENORM_NON_PBM_CLNT_TYP_CD as NON_PBM_CLNT_TYP_CD", " CLNT_ACCT_DENORM_NON_PBM_LOB_CD as NON_PBM_LOB_CD", 
      " DRUG_DRUG_PROD_GID as DRUG_PROD_GID", " PHMCY_CLM_EVNT_GID as LAST_FILL_CLM_GID", 
      " PHMCY_FILL_DT as LAST_FILL_DT", " PHMCY_MBR_ACCT_GID as MBR_ACCT_GID", " MBR_ACC_CVRG_CVRG_EFF_DT as CVRG_EFF_DT", 
      " MBR_ACC_CVRG_CVRG_EXPRN_DT as CVRG_EXPRN_DT", " MBR_ACC_CONT_CVRG_ELIG_CC_EFF_DT as ELIG_CC_EFF_DT", 
      " MBR_ACC_CONT_CVRG_ELIG_CC_EXPRN_DT as ELIG_CC_EXPRN_DT", " PHMCY_DENORM_PHMCY_PTY_GID as PHMCY_PTY_GID", " PHMCY_DENORM_CVS_MAIL_IND as CVS_MAIL_IND", 
      " PHMCY_SRC_CD as CLM_SRC_CD", " PHMCY_PRSCBR_PTY_GID as PRSCBR_PTY_GID", " PHMCY_DLVRY_SYSTM_CD as DLVRY_SYSTM_CD", 
      " PHMCY_DAY_SPLY_QTY as DAY_SPLY_QTY", "NORMALIZED_DAY_SPLY_QTY as NORMALIZED_DAY_SPLY_QTY", " PHMCY_ADJD_FRMLY_CD as ADJD_FRMLY_CD", 
      " PHMCY_MEDD_CLM_IND as MEDD_CLM_IND", " MBR_ACC_GNDR_CD as GNDR_CD",  " MBR_CURR_AGE as MBR_CURR_AGE", 
      " MINOR_IND as MINOR_IND", " MBR_CURR_ELIG_IND as MBR_CURR_ELIG_IND", " RTM_IND as RTM_IND", "MCV_IND as MCV_IND", 
      " RTM_IND as RFM_IND", 
      " FFM_IND as FFM_IND", 
      " CONTROLLED_SUBSTANCE_IND as CONTROLLED_SUBSTANCE_IND", " DRUG_BUS_MAINT_IND as MAINTENANCE_IND", 
      " PHMCY_PHMCY_LTC_IND as PHMCY_LTC_IND", " DRUG_SPCLT_DRUG_IND as SPCLT_DRUG_IND",
      createTms)
  
  return (transformedTable)
}